# Generated by Django 2.2.4 on 2019-09-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fold_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='image',
        ),
    ]
