# Generated by Django 2.2.4 on 2019-09-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fold_menu', '0002_auto_20190912_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
